name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: YusraAnum
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Commit and push
        run: |
          git add dist/github-contribution-grid-snake-dark.svg
          git commit -m "Generate Snake" || echo "No changes to commit"
          git push
